# Increase Gradle Daemon heap size
org.gradle.jvmargs=-Xmx2048m --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED

# Enable Gradle build caching
org.gradle.caching=true

# Enable parallel execution
org.gradle.parallel=true

# AndroidX flags
android.useAndroidX=true
android.enableJetifier=true
